FROM python:3.11-slim
WORKDIR /app

COPY project/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5001

CMD ["python", "-c", "from rq import Worker, Queue, Connection; from redis import Redis; conn = Redis.from_url('redis://redis:6379'); w = Worker(Queue(connection=conn), connection=conn); w.work()"]